os: linux
dist: trusty
sudo: required
group: stable
language: c
services:
  - docker

before_install:
  - docker pull miladiir/vitasdk
  - docker run miladiir/vitasdk /bin/sh -l -c "vitasdk-update"

install:
  -  docker run miladiir/vitasdk /bin/sh -l -c "cmake"
