os: linux
dist: trusty
sudo: required
group: stable
language: c
services:
  - docker

before_install:
  - docker pull miladiir/vitasdk
  - docker run miladiir/vitasdk /bin/sh -c "source /root/.bashrc; vitasdk-update"

install:
  -  docker run miladiir/vitasdk /bin/sh -c "source /root/.bashrc; cmake"
