os: linux
dist: trusty
sudo: required
group: stable
language: c
cache:
  directories:
   - $HOME/local/vitasdk

env:
  global:
    - VITASDK=$HOME/local/vitasdk
    - VDPMPATH=$HOME/local/vdpm


before_install:
  - mkdir -v -p $VITASDK
  - git clone https://github.com/vitasdk/vdpm $VDPMPATH
  - cd $VDPMPATH && pwd
  - ./bootstrap-vitasdk.sh

install:
  - export PATH="$VITASDK:$PATH"
  - cd $VDPMPATH && pwd
  - ./install-all.sh

script:
  - export PATH="$VITASDK:$PATH"
  - cmake
