sudo: required

language: c

services:
  - docker

before_install:
  - docker pull miladiir/vitasdk
  - docker run miladiir/vitasdk /bin/sh -c "vitasdk-update"

install:
  -  docker run miladiir/vitasdk /bin/sh -c "cmake"
