os: linux
dist: trusty
sudo: required
group: stable
language: c
services:
  - docker

before_install:
  - docker pull miladiir/vitasdk
  - docker run miladiir/vitasdk /bin/sh -l -c "VITASDK=/usr/local/vitasdk PATH=$VITASDK/bin:$PATH vitasdk-update"

install:
  -  docker run miladiir/vitasdk /bin/sh -l -c ""VITASDK=/usr/local/vitasdk PATH=$VITASDK/bin:$PATH cmake"
